#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk-sut/rustdesk-sut /usr/bin/rustdesk-sut

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/rustdesk-sut.service ]; then
			rm /etc/systemd/system/rustdesk-sut.service /usr/lib/systemd/system/rustdesk-sut.service /usr/lib/systemd/user/rustdesk-sut.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk-sut/files/systemd/rustdesk-sut.service /usr/lib/systemd/system/rustdesk-sut.service
		# try fix error in Ubuntu 18.04
		# Failed to reload rustdesk-sut.service: Unit rustdesk-sut.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/rustdesk-sut.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/rustdesk-sut.service
		fi
		systemctl daemon-reload
		systemctl enable rustdesk-sut
		systemctl start rustdesk-sut
	fi
fi
